# copy from environment.yaml in project root
name: readthedocs
channels:
  - conda-forge
  - defaults
dependencies:
  - gmsh
  - jax==0.5.0
  - jaxopt
  - numpy
  - pygmo
  - python==3.12
  - python-gmsh
  - trame
  - ipywidgets
  - scipy
  - scikit-learn
  - pyvista
  - typeguard
  - yaml
  - pygraphviz
  - pip
  - pip:
      - sphinx-rtd-theme
      - myst-parser[linkify]
      - sphinx>=3.2.1
      - git+https://github.com/cpml-au/dctkit
      - git+https://github.com/cpml-au/deap
      - ray
      - pygmsh
      - tox
      - mygrad
      - tox-conda
      - pmlb
      - optuna
      - optuna-integration
      - sympy
